#!/bin/sh
#***********************************************************************
#*                   GNU Lesser General Public License
#*
#* This file is part of the SHiELD Build System.
#*
#* The SHiELD Build System free software: you can redistribute it
#* and/or modify it under the terms of the
#* GNU Lesser General Public License as published by the
#* Free Software Foundation, either version 3 of the License, or
#* (at your option) any later version.
#*
#* The SHiELD Build System distributed in the hope that it will be
#* useful, but WITHOUT ANYWARRANTY; without even the implied warranty
#* of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#* See the GNU General Public License for more details.
#*
#* You should have received a copy of the GNU Lesser General Public
#* License along with theSHiELD Build System
#* If not, see <http://www.gnu.org/licenses/>.
#***********************************************************************
#
#  DISCLAIMER: This script is provided as-is and as such is unsupported.
#

. ${MODULESHOME}/init/sh
module load git

export SHiELD_SRC=${PWD%/*}/SHiELD_SRC/

mkdir -p ${SHiELD_SRC}
cd ${SHiELD_SRC}

release="shiemom"

fv3_release=$release
phy_release=$release
fms_release="$release"
drivers_release="$release"
atmosnull_release="$release"
ocean_release="$release"
land_release="$release"
ice_release="$release"

git clone -b ${fv3_release}   https://github.com/JosephMouallem/GFDL_atmos_cubed_sphere
git clone -b ${phy_release}   https://github.com/JosephMouallem/SHiELD_physics
git clone -b ${fms_release}   https://github.com/JosephMouallem/FMS
git clone -b ${fms_release}   https://github.com/JosephMouallem/FMSCoupler
git clone -b ${drivers_release}   https://github.com/JosephMouallem/atmos_drivers
git clone -b ${atmosnull_release}   https://github.com/JosephMouallem/atmos_null
git clone -b ${ocean_release}   https://github.com/JosephMouallem/ocean_null
git clone -b ${land_release}   https://github.com/JosephMouallem/land_null
git clone -b ${ice_release}   https://github.com/JosephMouallem/ice_null
git clone  https://github.com/NOAA-GFDL/ice_param

#Automatic release tracking from Matt M.
echo $release > release

cd ../SHiELD_build/
./CHECKOUT_mom6.csh
###
###git clone -q --recursive -b master https://github.com/NOAA-GFDL/ocean_BGC.git
###cd ocean_BGC
###git checkout 2023.01
###git clone -b dev/gfdl https://github.com/NOAA-GFDL/MOM6-examples.git mom6
###pushd mom6
###git checkout 3220014e
###git submodule update --recursive --init src/MOM6 src/SIS2 src/icebergs
###(cd src/icebergs && git checkout dev/gfdl)
###if ("fffb6f35" != "") then
###  echo WARNING: Checking out from a fork! Work in progress
###  (cd src/MOM6;git checkout fffb6f35; )
###endif
###if ("fac2ec43" != "") then
###  echo WARNING: Checking out from a fork! Work in progress
###  (cd src/SIS2;git checkout fac2ec43; )
###endif
###popd
###
###pushd mom6
###set platform_domain = `perl -T -e "use Net::Domain(hostdomain) ; print hostdomain"`
###if ("${platform_domain}" =~ *"MsState"* ) then
###  ln -s /work/noaa/gfdlscr/pdata/gfdl/gfdl_O/datasets/ .datasets
###else
###  ln -s /lustre/f2/pdata/gfdl/gfdl_O/datasets/ .datasets
###endif
###popd
###
###test -e mom6/.datasets
###if ($status != 0) then
###  echo ""; echo "" ; echo "   WARNING:  .datasets link in MOM6 examples directory is invalid"; echo ""; echo ""
###endif
###
###echo -e "HERE"
###git clone https://gitlab.gfdl.noaa.gov/ogrp/Gaea-stats-MOM6-examples.git
###pushd Gaea-stats-MOM6-examples/regressions/ice_ocean_SIS2
####foreach stat ( `find . -name "ocean.stats.*"` )
####  cp $stat ../../../mom6/ice_ocean_SIS2/$stat
####end
###for stat in $(find . -name "ocean.stats.*"); do
###  cp "$stat" "../../../mom6/ice_ocean_SIS2/$stat"
###done
